//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "ZedCamera.hh"
#include "smartTimedTaskTrigger.h"
//FIXME: implement logging
//#include "smartGlobalLogger.hh"

// the ace port-factory is used as a default port-mapping
#include "ZedCameraAcePortFactory.hh"


// initialize static singleton pointer to zero
ZedCamera* ZedCamera::_zedCamera = 0;

// constructor
ZedCamera::ZedCamera()
{
	std::cout << "constructor of ZedCamera\n";
	
	// set all pointer members to NULL
	getImage = NULL;
	getImageTrigger = NULL;
	pointCloudPushServiceOut = NULL;
	rGBDImagePushServiceOut = NULL;
	rGBImagePushServiceOut = NULL;
	stateChangeHandler = NULL;
	stateSlave = NULL;
	wiringSlave = NULL;
	
	// set default ini parameter values
	connections.component.name = "ZedCamera";
	connections.component.initialComponentMode = "Neutral";
	connections.component.defaultScheduler = "DEFAULT";
	connections.component.useLogger = false;
	
	connections.pointCloudPushServiceOut.serviceName = "PointCloudPushServiceOut";
	connections.pointCloudPushServiceOut.roboticMiddleware = "ACE_SmartSoft";
	connections.rGBDImagePushServiceOut.serviceName = "RGBDImagePushServiceOut";
	connections.rGBDImagePushServiceOut.roboticMiddleware = "ACE_SmartSoft";
	connections.rGBImagePushServiceOut.serviceName = "RGBImagePushServiceOut";
	connections.rGBImagePushServiceOut.roboticMiddleware = "ACE_SmartSoft";
	connections.getImage.minActFreq = 0.0;
	connections.getImage.maxActFreq = 0.0;
	// scheduling default parameters
	connections.getImage.scheduler = "DEFAULT";
	connections.getImage.priority = -1;
	connections.getImage.cpuAffinity = -1;
	
	// initialize members of OpcUaBackendComponentGeneratorExtension
	
	// initialize members of PlainOpcUaZedCameraExtension
	
	// initialize members of ZedCameraROSExtension
	
}

void ZedCamera::addPortFactory(const std::string &name, ZedCameraPortFactoryInterface *portFactory)
{
	portFactoryRegistry[name] = portFactory;
}

void ZedCamera::addExtension(ZedCameraExtension *extension)
{
	componentExtensionRegistry[extension->getName()] = extension;
}

SmartACE::SmartComponent* ZedCamera::getComponentImpl()
{
	return dynamic_cast<ZedCameraAcePortFactory*>(portFactoryRegistry["ACE_SmartSoft"])->getComponentImpl();
}

/**
 * Notify the component that setup/initialization is finished.
 * You may call this function from anywhere in the component.
 *
 * Set component's internal lifecycle state automaton (if any) into 
 * Alive mode (from here on the component is ready to provide its services)
 */
void ZedCamera::setStartupFinished() {
	stateSlave->setWaitState("Alive");
	std::cout << "ComponentDefinition initialization/startup finished." << std::endl;
}




/**
 * First connect ALL client ports contained in this component, then start all services:
 * activate state, push, etc...
 */
Smart::StatusCode ZedCamera::connectAndStartAllServices() {
	Smart::StatusCode status = Smart::SMART_OK;
	
	return status;
}

/**
 * Start all tasks contained in this component.
 */
void ZedCamera::startAllTasks() {
	// start task GetImage
	if(connections.getImage.scheduler != "DEFAULT") {
		ACE_Sched_Params getImage_SchedParams(ACE_SCHED_OTHER, ACE_THR_PRI_OTHER_DEF);
		if(connections.getImage.scheduler == "FIFO") {
			getImage_SchedParams.policy(ACE_SCHED_FIFO);
			getImage_SchedParams.priority(ACE_THR_PRI_FIFO_MIN);
		} else if(connections.getImage.scheduler == "RR") {
			getImage_SchedParams.policy(ACE_SCHED_RR);
			getImage_SchedParams.priority(ACE_THR_PRI_RR_MIN);
		}
		getImage->start(getImage_SchedParams, connections.getImage.cpuAffinity);
	} else {
		getImage->start();
	}
}

/**
 * Start all timers contained in this component
 */
void ZedCamera::startAllTimers() {
}


Smart::TaskTriggerSubject* ZedCamera::getInputTaskTriggerFromString(const std::string &client)
{
	
	return NULL;
}


void ZedCamera::init(int argc, char *argv[])
{
	try {
		Smart::StatusCode status;
		
		// load initial parameters from ini-file (if found)
		loadParameter(argc, argv);
		
		
		// initializations of OpcUaBackendComponentGeneratorExtension
		
		// initializations of PlainOpcUaZedCameraExtension
		
		// initializations of ZedCameraROSExtension
		
		
		// initialize all registered port-factories
		for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
		{
			portFactory->second->initialize(this, argc, argv);
		}
		
		// initialize all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->initialize(this, argc, argv);
		}
		
		ZedCameraPortFactoryInterface *acePortFactory = portFactoryRegistry["ACE_SmartSoft"];
		if(acePortFactory == 0) {
			std::cerr << "ERROR: acePortFactory NOT instantiated -> exit(-1)" << std::endl;
			exit(-1);
		}
		
		// this pointer is used for backwards compatibility (deprecated: should be removed as soon as all patterns, including coordination, are moved to port-factory)
		SmartACE::SmartComponent *component = dynamic_cast<ZedCameraAcePortFactory*>(acePortFactory)->getComponentImpl();
		
		std::cout << "ComponentDefinition ZedCamera is named " << connections.component.name << std::endl;
		
		if(connections.component.useLogger == true) {
			//FIXME: use logging
			//Smart::LOGGER->openLogFileInFolder("data/"+connections.component.name);
			//Smart::LOGGER->startLogging();
		}

		// create event-test handlers (if needed)
		
		// create server ports
		// TODO: set minCycleTime from Ini-file
		pointCloudPushServiceOut = portFactoryRegistry[connections.pointCloudPushServiceOut.roboticMiddleware]->createPointCloudPushServiceOut(connections.pointCloudPushServiceOut.serviceName);
		rGBDImagePushServiceOut = portFactoryRegistry[connections.rGBDImagePushServiceOut.roboticMiddleware]->createRGBDImagePushServiceOut(connections.rGBDImagePushServiceOut.serviceName);
		rGBImagePushServiceOut = portFactoryRegistry[connections.rGBImagePushServiceOut.roboticMiddleware]->createRGBImagePushServiceOut(connections.rGBImagePushServiceOut.serviceName);
		
		// create client ports
		
		// create InputTaskTriggers and UpcallManagers
		
		// create input-handler
		
		// create request-handlers
		
		// create state pattern
		stateChangeHandler = new SmartStateChangeHandler();
		stateSlave = new SmartACE::StateSlave(component, stateChangeHandler);
		status = stateSlave->setUpInitialState(connections.component.initialComponentMode);
		if (status != Smart::SMART_OK) std::cerr << status << "; failed setting initial ComponentMode: " << connections.component.initialComponentMode << std::endl;
		// activate state slave
		status = stateSlave->activate();
		if(status != Smart::SMART_OK) std::cerr << "ERROR: activate state" << std::endl;
		
		wiringSlave = new SmartACE::WiringSlave(component);
		// add client port to wiring slave
		
		
		
		// create Task GetImage
		getImage = new GetImage(component);
		// configure input-links
		// configure task-trigger (if task is configurable)
		if(connections.getImage.trigger == "PeriodicTimer") {
			// create PeriodicTimerTrigger
			int microseconds = 1000*1000 / connections.getImage.periodicActFreq;
			if(microseconds > 0) {
				Smart::TimedTaskTrigger *triggerPtr = new Smart::TimedTaskTrigger();
				triggerPtr->attach(getImage);
				component->getTimerManager()->scheduleTimer(triggerPtr, (void *) 0, std::chrono::microseconds(microseconds), std::chrono::microseconds(microseconds));
				// store trigger in class member
				getImageTrigger = triggerPtr;
			} else {
				std::cerr << "ERROR: could not set-up Timer with cycle-time " << microseconds << " as activation source for Task GetImage" << std::endl;
			}
		} else if(connections.getImage.trigger == "DataTriggered") {
			getImageTrigger = getInputTaskTriggerFromString(connections.getImage.inPortRef);
			if(getImageTrigger != NULL) {
				getImageTrigger->attach(getImage, connections.getImage.prescale);
			} else {
				std::cerr << "ERROR: could not set-up InPort " << connections.getImage.inPortRef << " as activation source for Task GetImage" << std::endl;
			}
		} 
		
		
		// link observers with subjects
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std exception" << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}

// run the component
void ZedCamera::run()
{
	stateSlave->acquire("init");
	// startup all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onStartup();
	}
	
	// startup all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onStartup();
	}
	stateSlave->release("init");
	
	// do not call this handler within the init state (see above) as this handler internally calls setStartupFinished() (this should be fixed in future)
	compHandler.onStartup();
	
	// this call blocks until the component is commanded to shutdown
	stateSlave->acquire("shutdown");
	
	// shutdown all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onShutdown();
	}
	
	// shutdown all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onShutdown();
	}
	
	if(connections.component.useLogger == true) {
		//FIXME: use logging
		//Smart::LOGGER->stopLogging();
	}
	
	compHandler.onShutdown();
	
	stateSlave->release("shutdown");
}

// clean-up component's resources
void ZedCamera::fini()
{
	// unlink all observers
	
	// destroy all task instances
	// unlink all UpcallManagers
	// unlink the TaskTrigger
	if(getImageTrigger != NULL){
		getImageTrigger->detach(getImage);
		delete getImage;
	}

	// destroy all input-handler

	// destroy InputTaskTriggers and UpcallManagers

	// destroy client ports

	// destroy server ports
	delete pointCloudPushServiceOut;
	delete rGBDImagePushServiceOut;
	delete rGBImagePushServiceOut;
	// destroy event-test handlers (if needed)
	
	// destroy request-handlers
	
	delete stateSlave;
	// destroy state-change-handler
	delete stateChangeHandler;
	
	// destroy all master/slave ports
	delete wiringSlave;
	

	// destroy all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->destroy();
	}

	// destroy all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->destroy();
	}
	
	// destruction of OpcUaBackendComponentGeneratorExtension
	
	// destruction of PlainOpcUaZedCameraExtension
	
	// destruction of ZedCameraROSExtension
	
}

void ZedCamera::loadParameter(int argc, char *argv[])
{
	/*
	 Parameters can be specified via command line --filename=<filename> or -f <filename>

	 With this parameter present:
	   - The component will look for the file in the current working directory,
	     a path relative to the current directory or any absolute path
	   - The component will use the default values if the file cannot be found

	 With this parameter absent:
	   - <Name of Component>.ini will be read from current working directory, if found there
	   - $SMART_ROOT/etc/<Name of Component>.ini will be read otherwise
	   - Default values will be used if neither found in working directory or /etc
	 */
	SmartACE::SmartIniParameter parameter;
	std::ifstream parameterfile;
	bool parameterFileFound = false;

	// load parameters
	try
	{
		// if paramfile is given as argument
		if(parameter.tryAddFileFromArgs(argc,argv,"filename", 'f'))
		{
			parameterFileFound = true;
			std::cout << "parameter file is loaded from an argv argument \n";
		} else if(parameter.searchFile("ZedCamera.ini", parameterfile)) {
			parameterFileFound = true;
			std::cout << "load ZedCamera.ini parameter file\n";
			parameter.addFile(parameterfile);
		} else {
			std::cout << "WARNING: ZedCamera.ini parameter file not found! (using default values or command line arguments)\n";
		}
		
		// add command line arguments to allow overwriting of parameters
		// from file
		parameter.addCommandLineArgs(argc,argv,"component");
		
		// initialize the naming service using the command line parameters parsed in the
		// SmartIniParameter class. The naming service parameters are expected to be in
		// the "component" parameter group.
		SmartACE::NAMING::instance()->checkForHelpArg(argc,argv);
		if(parameterFileFound) 
		{
			if(SmartACE::NAMING::instance()->init(parameter.getAllParametersFromGroup("component")) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		} else {
			if(SmartACE::NAMING::instance()->init(argc, argv) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		}
			
		// print all known parameters
		// parameter.print();
		
		//--- server port // client port // other parameter ---
		// load parameter
		parameter.getString("component", "name", connections.component.name);
		parameter.getString("component", "initialComponentMode", connections.component.initialComponentMode);
		if(parameter.checkIfParameterExists("component", "defaultScheduler")) {
			parameter.getString("component", "defaultScheduler", connections.component.defaultScheduler);
		}
		if(parameter.checkIfParameterExists("component", "useLogger")) {
			parameter.getBoolean("component", "useLogger", connections.component.useLogger);
		}
		
		
		// load parameters for server PointCloudPushServiceOut
		parameter.getString("PointCloudPushServiceOut", "serviceName", connections.pointCloudPushServiceOut.serviceName);
		if(parameter.checkIfParameterExists("PointCloudPushServiceOut", "roboticMiddleware")) {
			parameter.getString("PointCloudPushServiceOut", "roboticMiddleware", connections.pointCloudPushServiceOut.roboticMiddleware);
		}
		// load parameters for server RGBDImagePushServiceOut
		parameter.getString("RGBDImagePushServiceOut", "serviceName", connections.rGBDImagePushServiceOut.serviceName);
		if(parameter.checkIfParameterExists("RGBDImagePushServiceOut", "roboticMiddleware")) {
			parameter.getString("RGBDImagePushServiceOut", "roboticMiddleware", connections.rGBDImagePushServiceOut.roboticMiddleware);
		}
		// load parameters for server RGBImagePushServiceOut
		parameter.getString("RGBImagePushServiceOut", "serviceName", connections.rGBImagePushServiceOut.serviceName);
		if(parameter.checkIfParameterExists("RGBImagePushServiceOut", "roboticMiddleware")) {
			parameter.getString("RGBImagePushServiceOut", "roboticMiddleware", connections.rGBImagePushServiceOut.roboticMiddleware);
		}
		
		// load parameters for task GetImage
		parameter.getDouble("GetImage", "minActFreqHz", connections.getImage.minActFreq);
		parameter.getDouble("GetImage", "maxActFreqHz", connections.getImage.maxActFreq);
		parameter.getString("GetImage", "triggerType", connections.getImage.trigger);
		if(connections.getImage.trigger == "PeriodicTimer") {
			parameter.getDouble("GetImage", "periodicActFreqHz", connections.getImage.periodicActFreq);
		} else if(connections.getImage.trigger == "DataTriggered") {
			parameter.getString("GetImage", "inPortRef", connections.getImage.inPortRef);
			parameter.getInteger("GetImage", "prescale", connections.getImage.prescale);
		}
		if(parameter.checkIfParameterExists("GetImage", "scheduler")) {
			parameter.getString("GetImage", "scheduler", connections.getImage.scheduler);
		}
		if(parameter.checkIfParameterExists("GetImage", "priority")) {
			parameter.getInteger("GetImage", "priority", connections.getImage.priority);
		}
		if(parameter.checkIfParameterExists("GetImage", "cpuAffinity")) {
			parameter.getInteger("GetImage", "cpuAffinity", connections.getImage.cpuAffinity);
		}
		
		// load parameters for OpcUaBackendComponentGeneratorExtension
		
		// load parameters for PlainOpcUaZedCameraExtension
		
		// load parameters for ZedCameraROSExtension
		
		
		// load parameters for all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->loadParameters(parameter);
		}
		
	
	} catch (const SmartACE::IniParameterError & e) {
		std::cerr << e.what() << std::endl;
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std::exception: " << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}
