//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "SensorZR300OpcUaBackendPortFactory.hh"

// include all potentially required pattern implementations
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/PushClient.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/EventClient.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/QClientOPCUA.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/SendClient.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/QueryClient.hpp>

#include <SeRoNetSDK/SeRoNet/OPCUA/Server/PushServer.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Server/EventServer.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Server/SendServer.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Server/QueryServer.hpp>

// include referenced CommunicationObject SeRoNetSDK self description implementations
#include "DomainVisionOpcUa/Comm3dPointCloudOpcUa.hh"
#include "DomainVisionOpcUa/CommRGBDImageOpcUa.hh"
#include "DomainVisionOpcUa/CommVideoImageOpcUa.hh"

// create a static instance of the OpcUaBackendPortFactory
static SensorZR300OpcUaBackendPortFactory OpcUaBackendPortFactory;

SensorZR300OpcUaBackendPortFactory::SensorZR300OpcUaBackendPortFactory()
{  
	componentImpl = 0;
	SensorZR300::instance()->addPortFactory("OpcUa_SeRoNet", this);
}

SensorZR300OpcUaBackendPortFactory::~SensorZR300OpcUaBackendPortFactory()
{  }

void SensorZR300OpcUaBackendPortFactory::initialize(SensorZR300 *component, int argc, char* argv[])
{
	componentImpl = new SeRoNet::Utils::Component(component->connections.component.name);
}

int SensorZR300OpcUaBackendPortFactory::onStartup()
{
	if (!component_thread.joinable()) {
    	component_thread = std::thread(&SensorZR300OpcUaBackendPortFactory::task_execution, this);
    	return 0;
    }
	return -1;
}


Smart::IPushServerPattern<DomainVision::Comm3dPointCloud> * SensorZR300OpcUaBackendPortFactory::createPointCloudPushServiceOut(const std::string &serviceName)
{
	return new SeRoNet::OPCUA::Server::PushServer<DomainVision::Comm3dPointCloud>(componentImpl, serviceName);
}

Smart::IPushServerPattern<DomainVision::CommRGBDImage> * SensorZR300OpcUaBackendPortFactory::createRGBDImagePushServiceOut(const std::string &serviceName)
{
	return new SeRoNet::OPCUA::Server::PushServer<DomainVision::CommRGBDImage>(componentImpl, serviceName);
}

Smart::IPushServerPattern<DomainVision::CommVideoImage> * SensorZR300OpcUaBackendPortFactory::createRGBImagePushServiceOut(const std::string &serviceName)
{
	return new SeRoNet::OPCUA::Server::PushServer<DomainVision::CommVideoImage>(componentImpl, serviceName);
}


int SensorZR300OpcUaBackendPortFactory::task_execution()
{
	componentImpl->run();
	return 0;
}

int SensorZR300OpcUaBackendPortFactory::onShutdown(const std::chrono::steady_clock::duration &timeoutTime)
{
	// stop component-internal infrastructure
	componentImpl->stopRunning();
	// wait on component thread to exit
	if (component_thread.joinable()) {
		// FIXME: don't wait infinetly (use timeoutTime here)
    	component_thread.join();
    }
	return 0;
}

void SensorZR300OpcUaBackendPortFactory::destroy()
{
	// clean-up component's internally used resources
	delete componentImpl;
}
