//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#ifndef SENSORZR300_OPC_UA_BACKEND_PORTFACTORY_HH_
#define SENSORZR300_OPC_UA_BACKEND_PORTFACTORY_HH_

// include the main component-definition class
#include "SensorZR300PortFactoryInterface.hh"

#include <thread>
#include <chrono>

// include SeRoNetSDK library
#include <SeRoNetSDK/SeRoNet/Utils/Task.hpp>
#include <SeRoNetSDK/SeRoNet/Utils/Component.hpp>

class SensorZR300OpcUaBackendPortFactory: public SensorZR300PortFactoryInterface
{
private:
	// internal component instance
	SeRoNet::Utils::Component *componentImpl;
	
	// component thread
	std::thread component_thread;
	
	// internal component thread method
	int task_execution();
public:
	SensorZR300OpcUaBackendPortFactory();
	virtual ~SensorZR300OpcUaBackendPortFactory();

	virtual void initialize(SensorZR300 *component, int argc, char* argv[]) override;
	virtual int onStartup() override;

	
	virtual Smart::IPushServerPattern<DomainVision::Comm3dPointCloud> * createPointCloudPushServiceOut(const std::string &serviceName) override;
	virtual Smart::IPushServerPattern<DomainVision::CommRGBDImage> * createRGBDImagePushServiceOut(const std::string &serviceName) override;
	virtual Smart::IPushServerPattern<DomainVision::CommVideoImage> * createRGBImagePushServiceOut(const std::string &serviceName) override;
	
	virtual int onShutdown(const std::chrono::steady_clock::duration &timeoutTime=std::chrono::seconds(2)) override;
	virtual void destroy() override;
};

#endif /* SENSORZR300_SERONET_SDK_PORTFACTORY_HH_ */
